### ISSUE TITLE
Disable notifications for improved concentration

### ISSUE THREAD

**Issue by jakob1379** [kdani3/i3-gnome-pomodoro#29]
Would it make sense to implement some way to disable notifications? For dunst it can be done in an none invasive way, as described [here](https://wiki.archlinux.org/index.php/Dunst#Disable_dunst_temporarily)

**Comment by jakob1379** [comment]
Didn't see it was actually an option in gnome-pomodoro itself. Close issue, unless it should be an option available in i3-gnome-pomodoro as well?

**Comment by kantord** [comment]
It is already a feature with dunst!

**Comment by kantord** [comment]
https://github.com/kantord/i3-gnome-pomodoro#suppressing-dunst-notifications-and-disabling-workspaces

**Comment by jakob1379** [comment]
Though it doesn't block all notifications as of my test just now. Also I found that for dunst `notify-send "DUNST_COMMAND_TOGGLE`, `notify-send "DUNST_COMMAND_RESUME`, and `notify-send "DUNST_COMMAND_PAUSE` worked perfectly.

But again I don't think this should be in i3-gnome-pomodoro unless you want a broader notification blocking system.

**Comment by kantord** [comment]
ah ok, I thought you meant blocking all notifications in your system, not just gnome-pomodoro!

I think it doesn't make sense to duplicate all the configuration options, since you can just change them in gnome-pomodoro.

We could go that way, but I guess then it would eventually not make sense to even make the user install gnome-pomodoro, we could just implement the timer in this project.

**Comment by jakob1379** [comment]
Yeah I agree that it should be held as an extension for the most part. I really like their GUI so I wouldn't want to give up on that. Let's leave it at that.
